sonar.projectKey=Norlik13_CEZI_zen
sonar.organization=norlik13

sonar.projectName=CESIZen
sonar.projectVersion=1.0

# Sources analysées
sonar.sources=accounts,infos,emotions,CEZIZen
sonar.tests=accounts,infos,emotions
sonar.test.inclusions=**/tests.py,**/test_*.py,**/tests_integration.py

sonar.python.version=3.13

# Rapport de couverture généré par coverage.py
sonar.python.coverage.reportPaths=coverage.xml

# Exclusions
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/.venv/**,**/static/**,tests_integration.py

sonar.sourceEncoding=UTF-8
