blank_issues_enabled: false

contact_links:
  - name: Documentation CESIZen
    url: https://github.com/Norlik13/CEZI_zen/blob/master/README.md
    about: Consulter la documentation avant d'ouvrir une issue
