# Generated by Django 6.0 on 2026-03-05 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=60, unique=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=60)),
                ('actif', models.BooleanField(default=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotions', to='emotions.emotionbase')),
            ],
            options={
                'unique_together': {('base', 'libelle')},
            },
        ),
        migrations.CreateModel(
            name='TrackerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('intensite', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emotions.emotion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
