# Generated by Django 6.0 on 2026-03-05 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=80)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('contenu', models.TextField()),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=10)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuEntree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=80)),
                ('ordre_affichage', models.PositiveIntegerField(default=0)),
                ('url_externe', models.URLField(blank=True, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrees', to='infos.menu')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infos.pageinformation')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('page__isnull', False), ('url_externe__isnull', True)), models.Q(('page__isnull', True), ('url_externe__isnull', False)), _connector='OR'), name='menuentree_page_xor_url')],
            },
        ),
    ]
