# Generated by Django 6.0 on 2026-04-01 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='menuentree',
            name='menuentree_page_xor_url',
        ),
        migrations.RemoveField(
            model_name='menuentree',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='menuentree',
            name='page',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuEntree',
        ),
    ]
